/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LibraryFrame;

import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 227001
 */
public class IssueBook extends javax.swing.JFrame {

    
    int bookId , memId;
    String bookName,memName;
    public IssueBook() {
        initComponents();
        showIssuedBook();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bookIdTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        memIdTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        issDate = new rojeru_san.componentes.RSDateChooser();
        retDate = new rojeru_san.componentes.RSDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        issueBtn = new javax.swing.JButton();
        bookNameLbl = new javax.swing.JLabel();
        memNameLbl = new javax.swing.JLabel();
        quantityLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Issue Book");
        jLabel5.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        issueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book ID", "Book Name", "Member ID", "Member Name", "Issue Date", "Return Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        issueTable.setShowGrid(true);
        jScrollPane1.setViewportView(issueTable);
        if (issueTable.getColumnModel().getColumnCount() > 0) {
            issueTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            issueTable.getColumnModel().getColumn(1).setPreferredWidth(40);
            issueTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOOK ID :");

        bookIdTxt.setBackground(new java.awt.Color(102, 153, 255));
        bookIdTxt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        bookIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 204)));
        bookIdTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookIdTxtFocusLost(evt);
            }
        });
        bookIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIdTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MEMBER ID :");

        memIdTxt.setBackground(new java.awt.Color(102, 153, 255));
        memIdTxt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        memIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 204)));
        memIdTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                memIdTxtFocusLost(evt);
            }
        });
        memIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memIdTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ISSUE DATE  :");

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RETURN DATE :");

        issDate.setColorBackground(new java.awt.Color(102, 102, 102));
        issDate.setColorButtonHover(new java.awt.Color(102, 102, 102));
        issDate.setColorDiaActual(new java.awt.Color(153, 153, 153));
        issDate.setColorForeground(new java.awt.Color(153, 0, 255));
        issDate.setPlaceholder("Select Issue Date");

        retDate.setColorBackground(new java.awt.Color(102, 102, 102));
        retDate.setColorButtonHover(new java.awt.Color(102, 102, 102));
        retDate.setColorDiaActual(new java.awt.Color(153, 153, 153));
        retDate.setColorForeground(new java.awt.Color(153, 0, 255));
        retDate.setPlaceholder("Select Return Date");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BOOK NAME :");

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MEMBER NAME :");

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("QUANTITY :");

        backBtn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        issueBtn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        issueBtn.setText("ISSUE BOOK");
        issueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBtnActionPerformed(evt);
            }
        });

        bookNameLbl.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        bookNameLbl.setForeground(new java.awt.Color(255, 255, 102));

        memNameLbl.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        memNameLbl.setForeground(new java.awt.Color(255, 255, 102));

        quantityLbl.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        quantityLbl.setForeground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(issueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(12, 12, 12)
                                .addComponent(memNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(memIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bookIdTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                        .addComponent(bookNameLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(quantityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(bookIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(bookNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(quantityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(memIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(memNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void getBookDetails(){
        bookId=Integer.parseInt(bookIdTxt.getText());

        try{
            DBconnection ob= new DBconnection();
            String sql="select * from books where bookId = ?";
            PreparedStatement pst=ob.con.prepareStatement(sql);
            
            pst.setInt(1, bookId);
            ResultSet rs =pst.executeQuery();
            
            if (rs.next()){
                bookNameLbl.setText(rs.getString("bookName"));
                quantityLbl.setText(rs.getString("quantity"));
            }
            else{
                JOptionPane.showMessageDialog(this, "Book ID not found!");
                bookNameLbl.setText("");
                quantityLbl.setText("");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //to get and display member details 
    public void getMemberDetails(){
        memId=Integer.parseInt(memIdTxt.getText());

        try{
            DBconnection ob= new DBconnection();
            String sql="select * from members where id = ?";
            PreparedStatement pst=ob.con.prepareStatement(sql);
            
            pst.setInt(1, memId);
            ResultSet rs =pst.executeQuery();
            
            if (rs.next()){
                memNameLbl.setText(rs.getString("name"));
            }
            else{
                JOptionPane.showMessageDialog(this, "Member not found!");
                memNameLbl.setText("");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    // to display issued book details in table
    private void showIssuedBook(){
        try{
            DBconnection ob= new DBconnection();
            ResultSet rs =ob.st.executeQuery("select * from issued_book");
        
            while(rs.next()){
                
                int issId=rs.getInt("issueId");
                bookId=rs.getInt("bookId");
                bookName=rs.getString("bookName");
                memId=rs.getInt("memId");
                memName=rs.getString("memName");
                java.sql.Date issDate=rs.getDate("issueDate");
                java.sql.Date dueDate=rs.getDate("dueDate");
            
                Object[] rowData={issId, bookId,bookName,memId,memName,issDate,dueDate};
                DefaultTableModel model= (DefaultTableModel)issueTable.getModel();
                model.addRow(rowData); 
        }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //to clear table
    private void clearTable(){
        DefaultTableModel model= (DefaultTableModel)issueTable.getModel();
        model.setRowCount(0);
    }
    
    //to insert isuued book details in database 
    private boolean issueBook(){
        boolean isIssued=false;

        bookId=Integer.parseInt(bookIdTxt.getText());
        memId=Integer.parseInt(memIdTxt.getText());
        bookName= bookNameLbl.getText();
        memName=memNameLbl.getText();
        
        
        Long d1= issDate.getDatoFecha().getTime();
        Long d2= retDate.getDatoFecha().getTime();
        
        java.sql.Date sIssueDate = new java.sql.Date(d1);
        java.sql.Date sReturnDate = new java.sql.Date(d2);
        
        try{
            DBconnection ob= new DBconnection();
            String sql="insert into issued_book(bookId,bookName,memId,"
                    +"memName, issueDate, dueDate)values(?,?,?,?,?,?)";
            PreparedStatement pst=ob.con.prepareStatement(sql);
            
            pst.setInt(1,bookId);
            pst.setString(2, bookName);
            pst.setInt(3,memId );
            pst.setString(4, memName);
            pst.setDate(5, sIssueDate);
            pst.setDate(6, sReturnDate);
            
            int rowCnt = pst.executeUpdate();
            if(rowCnt>0){
                isIssued=true;
            }

        }
        catch(Exception e){
            e.printStackTrace();
        }        
        
        return isIssued;
    }
    
    // to update the book quantity
    private void updateBookCount(){
        
        bookId=Integer.parseInt(bookIdTxt.getText());
        int quantity = Integer.parseInt(quantityLbl.getText());
        
        try{
            DBconnection ob= new DBconnection();
            String sql="update books set quantity = quantity - 1 where bookId = ?";
            PreparedStatement pst=ob.con.prepareStatement(sql);
            
            pst.setInt(1,bookId);
            
            int rowCount= pst.executeUpdate();
            if(rowCount>0){
                quantityLbl.setText(Integer.toString(quantity-1));
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }
    
    //to check if the book is already issued to the same member
    private boolean isAlreadyIssued(){
        boolean isIssued=false;
        
        bookId=Integer.parseInt(bookIdTxt.getText());
        memId=Integer.parseInt(memIdTxt.getText());
        
        try{
            DBconnection ob= new DBconnection();
            String sql="select * from issued_book where bookId = ? and memId = ?";
            PreparedStatement pst=ob.con.prepareStatement(sql);
            
            pst.setInt(1,bookId);
            pst.setInt(2,memId );
            
            ResultSet rs=pst.executeQuery();
             if(rs.next()){
                 isIssued=true;
             }

        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        
        return isIssued;
    }
    
    private void bookIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIdTxtActionPerformed

    private void memIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memIdTxtActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.hide();
        new Main().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void bookIdTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookIdTxtFocusLost
        if(!bookIdTxt.getText().equals("")){
            getBookDetails();
        }
    }//GEN-LAST:event_bookIdTxtFocusLost

    private void memIdTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memIdTxtFocusLost
        if(!memIdTxt.getText().equals("")){
            getMemberDetails();
        }
    }//GEN-LAST:event_memIdTxtFocusLost

    private void issueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBtnActionPerformed
        
        if(isAlreadyIssued()==false){
        int quantity = Integer.parseInt(quantityLbl.getText());
        if (quantity>0){
            if(issueBook()){
               JOptionPane.showMessageDialog(this, "Book Issued");
               clearTable();
               showIssuedBook();
               updateBookCount();
            }   
            else
                JOptionPane.showMessageDialog(this, "Book Not Issued");
        }
        else{
            JOptionPane.showMessageDialog(this, "Book Out Of Stock");
        }
        }
        else
          JOptionPane.showMessageDialog(this, "This Book is Already Issued to this Member");  
    }//GEN-LAST:event_issueBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bookIdTxt;
    private javax.swing.JLabel bookNameLbl;
    private rojeru_san.componentes.RSDateChooser issDate;
    private javax.swing.JButton issueBtn;
    private javax.swing.JTable issueTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField memIdTxt;
    private javax.swing.JLabel memNameLbl;
    private javax.swing.JLabel quantityLbl;
    private rojeru_san.componentes.RSDateChooser retDate;
    // End of variables declaration//GEN-END:variables
}
